'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, MapPin, ShieldCheck, Sun } from 'lucide-react';
import { PortalShell } from './portal-shell';
import { PortalCard } from './portal-card';
import { catalogue } from '@/data/catalogue';
const benefits=[{Icon:MapPin,title:'Prima la zona',text:'Esplora Carmagnola sulla nostra mappa.'},{Icon:Sun,title:'Dentro la casa',text:'Leggi gli spazi e approfondisci l’esposizione.'},{Icon:ShieldCheck,title:'Oltre il prezzo',text:'Consulta dati dichiarati, documenti e stime.'}];
export function PortalHome(){
 const [market,setMarket]=useState('acquisto');const [query,setQuery]=useState('');const router=useRouter();
 return <PortalShell><main id="contenuto"><section className="portal-hero container"><div className="portal-hero-copy"><p className="eyebrow">IL TUO PROSSIMO INDIRIZZO · CARMAGNOLA</p><h1>Una casa da trovare.<br/><em>Una scelta da capire.</em></h1><p>Parti dalla zona, esplora gli immobili e guarda oltre il prezzo: spazi, luce e costi per scegliere con più consapevolezza.</p><form className="portal-home-search" onSubmit={e=>{e.preventDefault();router.push('/'+market+'?q='+encodeURIComponent(query));}}><div className="portal-tabs"><button type="button" aria-pressed={market==='acquisto'} onClick={()=>setMarket('acquisto')}>Acquisto</button><button type="button" aria-pressed={market==='affitto'} onClick={()=>setMarket('affitto')}>Affitto</button></div><div className="portal-search-row"><label><MapPin size={18}/><input aria-label="Zona o indirizzo" placeholder="Carmagnola, un borgo, un indirizzo…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="primary-button">Cerca casa<ArrowRight size={18}/></button></div></form><small>Un progetto locale, con dati e fonti in chiaro.</small></div><div className="portal-hero-visual"><div className="property-photo photo-0" role="img" aria-label="Immagine dimostrativa di una villa con giardino"/><span>Spazi da immaginare,<br/>informazioni da conoscere.</span><small>Immagine dimostrativa</small></div></section>
 <section className="portal-benefits container">{benefits.map(({Icon,title,text})=><div key={title}><Icon/><h2>{title}</h2><p>{text}</p></div>)}</section>
 {(['sale','rent'] as const).map(m=><section className="portal-section container" key={m}><div className="portal-section-heading"><div><p className="eyebrow">{m==='sale'?'CASE DA CONOSCERE':'NUOVE POSSIBILITÀ'}</p><h2>{m==='sale'?'La tua prossima casa, a Carmagnola':'Uno spazio da vivere in affitto'}</h2><p>{m==='sale'?'Un annuncio da fonte reale, insieme alle proposte dimostrative.':'Proposte dimostrative per esplorare il nuovo catalogo.'}</p></div><Link className="outline-button" href={m==='sale'?'/acquisto':'/affitto'}>Vedi tutti<ArrowRight size={18}/></Link></div><div className="portal-grid">{(m==='sale'?[catalogue.find(l=>l.status==='real')!,...catalogue.filter(l=>l.market==='sale'&&l.sponsored).slice(0,3)]:catalogue.filter(l=>l.market==='rent')).map(l=><PortalCard listing={l} key={l.id}/>)}</div></section>)}
 <section className="portal-cta container"><p className="eyebrow">IL TERRITORIO È IL PUNTO DI PARTENZA</p><h2>Quale zona senti già un po’ tua?</h2><p>Dal centro ai borghi, inizia dalla mappa e scopri gli immobili.</p><Link className="primary-button" href="/acquisto">Esplora Carmagnola<ArrowRight size={18}/></Link></section></main></PortalShell>;
}
