'use client';
import type { SaleListing } from '@/types/listing';
import { money } from '@/lib/repository';
export function PurchaseInsights({listing}:{listing:SaleListing}){
 return <section className="purchase-insights"><h3>Prima di acquistare: costi e verifiche</h3>
 <p>Prezzo richiesto: <strong>€ {money(listing.price)}</strong>, pari a circa <strong>€ {money(Math.round(listing.price/listing.areaSqm))}/m²</strong> sui {listing.areaSqm} m² dichiarati. È il prezzo dell’annuncio, non una valutazione indipendente.</p>
 <div className="purchase-cards"><article><h4>APE disponibile · fotografia energetica del 2016</h4><p>Classe G, EPgl,nren 359,52 kWh/m² anno; superficie utile riscaldata 61,1 m². Consumi standard: 2.021 Nm³ di gas e 446 kWh elettrici annui per i servizi energetici certificati. Questi ultimi non rappresentano tutti gli elettrodomestici della famiglia.</p><p>APE 2016 200392 0118, via Piscina Giacomo 41, piano 1, foglio 100, particella 193, subalterno 105. Copia consultativa priva di valore legale, scadenza riportata 23/12/2026. Confermare subalterno e assenza di modifiche successive.</p></article><article><h4>“Nessuna spesa condominiale”</h4><p>È una dichiarazione dell’inserzionista. In una bifamiliare possono comunque esserci costi per tetto, facciate, scale comuni e cancello. Verificare ripartizione delle spese, lavori previsti e arretrati.</p><strong>Da chiedere: riepilogo delle spese comuni e accordi tra proprietari.</strong></article>
 <article><h4>Stato e interventi</h4><p>Buono stato e serramenti in PVC con doppi vetri sono dichiarati. Non provano l’isolamento complessivo o lo stato degli impianti. Controllare caldaia, copertura, umidità e impermeabilizzazione di terrazzo e balcone.</p><strong>Preventivi necessari prima di attribuire costi o risparmi ai lavori.</strong></article></div>
 <h4>Stima luce e gas · famiglia di 3 persone</h4>
 <p className="purchase-total"><strong>Spesa annua stimata per una famiglia di 3 persone: circa € 4.250</strong> · circa € 355 al mese come media annuale.<br/>Fascia indicativa al variare dei consumi: <strong>€ 3.730–4.810 l’anno</strong> (circa € 310–400 al mese). Stima basata su 2.300 Smc di gas e 3.000 kWh di elettricità all’anno, non sulle bollette della casa. La spesa effettiva dipende da abitudini, uso del riscaldamento e contratto di fornitura. La fascia non è un intervallo statistico né un preventivo.</p>
 <div className="purchase-cards"><article><h4>Gas · circa € 3.306/anno con i consumi ipotizzati</h4><p>Ipotesi: 2.300 Smc/anno × € 1,4372/Smc ≈ € 3.306. Riferimento medio complessivo del cliente tipo in tutela vulnerabilità, agosto 2026. A prezzo invariato: 2.000 Smc ≈ € 2.874; 2.600 Smc ≈ € 3.737.</p></article><article><h4>Elettricità · circa € 949/anno con i consumi ipotizzati</h4><p>Ipotesi: 3.000 kWh/anno × € 0,3163/kWh ≈ € 949. Riferimento medio complessivo del cliente tipo vulnerabile in Maggior Tutela, luglio–settembre 2026, tasse incluse. A prezzo invariato: 2.700 kWh ≈ € 854; 3.400 kWh ≈ € 1.075. Totale comprensivo degli ausiliari: non aggiungiamo di nuovo i 446 kWh dell’APE.</p></article></div>
 <details><summary>Ipotesi e metodo di calcolo</summary><p>Tre residenti, uso abituale dell’abitazione, circa 20 °C durante il riscaldamento, caldaia a gas per riscaldamento e acqua calda, cucina a gas, nessuna auto elettrica, pompa di calore o climatizzazione estiva intensiva. Non è una media statistica delle famiglie di tre persone.</p><p>Il gas parte dai 2.021 Nm³ standard dell’APE: assumendo Nm³ a 0 °C e Smc a 15 °C alla stessa pressione, equivalgono a circa 2.132 Smc. L’ipotesi di 2.300 Smc aggiunge un margine ipotetico per acqua calda di tre persone e cucina; la fascia 2.000–2.600 Smc esplora abitudini e clima diversi. Non si moltiplica il consumo per tre e non si scala l’APE da 61,1 a 95 m².</p><p>Ultimi riferimenti complessivi reperiti al 28/09/2026: gas agosto 2026 ed elettricità III trimestre 2026. Sono prezzi medi per i profili tipo della tutela, non una media di tutte le offerte italiane né la tariffa contrattuale di questa famiglia. Comprendono le componenti della bolletta, incluse quote fisse e imposte, ripartite sui consumi tipo; non aggiungiamo quote fisse una seconda volta.</p><p>Applichiamo questi costi medi ai consumi ipotizzati: è una proiezione semplificata, perché i profili di riferimento (1.100 Smc gas e 2.000 kWh luce, 3 kW) differiscono da quelli stimati per questa casa. Un calcolo tariffario preciso deve separare quote fisse, variabili e scaglioni fiscali. I prezzi sono mantenuti costanti per un anno: non è una previsione delle tariffe future. La fascia varia solo i consumi, non i prezzi.</p><p>Fonti dei valori: <a href="https://www.rainews.it/amp/articoli/2026/09/caro-bollette-arera-rialzo-del-gas-7-ad-agosto-rispetto-al-mese-precedente-af1ddf16-2d5d-4a16-8cd4-15bf96111526.html" target="_blank" rel="noopener noreferrer">RaiNews/ANSA, dati ARERA gas agosto 2026</a>; <a href="https://www.pmi.it/economia/mercati/491148/bolletta-luce-vulnerabili-maggior-tutela.html" target="_blank" rel="noopener noreferrer">PMI.it, dati ARERA elettricità III trimestre 2026</a>. <a href="https://www.arera.it/comunicati-stampa/dettaglio/nota-stampagas-arera-comunica-valore-materia-prima-servizio-tutela-vulnerabilita-agosto-2026" target="_blank" rel="noopener noreferrer">Comunicato ARERA gas</a>: la sola materia prima è distinta dal costo complessivo utilizzato qui. Aggiornamento manuale al 28/09/2026, non in tempo reale.</p></details>
 <p><strong>Esclusi:</strong> acqua, TARI, manutenzione caldaia, spese comuni, assicurazioni, eventuale IMU, mutuo e lavori. Questa è una stima delle sole utenze energetiche.</p>
 <p className="solar-note">Da chiarire prima di usare la stima per decidere: 61,1 m² riscaldati nell’APE e 95 m² nell’annuncio sono grandezze diverse. Verificare che attestato e annuncio riguardino la stessa unità e che tutti gli ambienti oggi riscaldati siano inclusi. Eventuali lavori dopo il 2016 possono cambiare molto il risultato.</p>
 <h4>Quanto serve oltre al prezzo</h4><ul><li><strong>Imposte:</strong> dipendono da venditore, regime IVA, requisiti prima casa e dati catastali. Senza questi elementi non mostriamo un totale fiscale.</li><li><strong>Notaio e agenzia:</strong> richiedere preventivi scritti, comprensivi di imposte e IVA dove applicabili, distinguendo gli importi già inclusi per evitare doppi conteggi.</li><li><strong>Mutuo, se richiesto:</strong> considerare anticipo, rata, perizia, istruttoria e assicurazioni. Confrontare il TAEG e il prospetto personalizzato della banca; nessuna rata stimata è un’offerta.</li><li><strong>Ingresso e lavori:</strong> aggiungere trasloco, arredi, allacci o volture e interventi preventivati. L’immobile è dichiarato non arredato.</li></ul>
 <h4>Punti da chiarire su questa casa</h4><ul><li>La pianta mostra un cucinino e un balcone, mentre il testo parla di angolo cottura e la scheda del portale indica assenza di balcone: chiedere quale rappresentazione corrisponde allo stato attuale.</li><li>Verificare superficie commerciale e calpestabile, pertinenze incluse e titolo di proprietà o uso esclusivo degli spazi esterni.</li><li>Primo piano senza ascensore: valutare accessibilità e utilizzo quotidiano.</li><li>Un tecnico deve verificare corrispondenza tra stato reale, planimetria catastale e documentazione edilizia. Il notaio verifica gli aspetti di propria competenza, inclusi titolarità e gravami.</li><li>Orientamento del terrazzo a ovest e balcone a sud indicati dall’utente: luce e ombre restano da verificare sul posto.</li></ul>
 <p className="solar-note">Oggi possiamo confrontare caratteristiche e prezzo richiesto; l’APE consente uno scenario energetico, ma non determina il costo complessivo di gestione o concludere che l’acquisto sia conveniente.</p>
 <p className="solar-source">Riferimenti: <a href={listing.sourceUrl??undefined} target="_blank" rel="noopener noreferrer">annuncio originale</a> · <a href="https://www.arera.it/consumatori/il-portale-consumi" target="_blank" rel="noopener noreferrer">ARERA: consumi storici</a> · <a href="https://www.arera.it/bolletta/bolletta-dellelettricita/consumo-consapevole" target="_blank" rel="noopener noreferrer">ARERA: confronto della spesa</a> · <a href="https://www.efficienzaenergetica.enea.it/servizi-per/cittadini/gli-incentivi-per-chi-realizza-gli-interventi-2.html" target="_blank" rel="noopener noreferrer">ENEA: APE</a> · <a href="https://www1.agenziaentrate.gov.it/web_app_entrate/guida_acquisto_casa.html" target="_blank" rel="noopener noreferrer">Agenzia delle Entrate: acquisto della casa</a>. Riferimenti consultati il 28/09/2026.</p>
 </section>;
}
