'use client';
import { useId, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { ScanLine } from 'lucide-react';
export function Button({variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'}){return <button className={`ui-button ui-button-${variant} ${className}`} {...props}/>;}
export function Badge({kind='info',children}:{kind?:'info'|'demo'|'declared'|'verified'|'derived'|'missing';children:ReactNode}){return <span className={`ui-badge ui-badge-${kind}`}>{children}</span>;}
export function StatePanel({kind='empty',title,children}:{kind?:'empty'|'loading'|'error';title:string;children?:ReactNode}){return <div className={`ui-state ui-state-${kind}`} role={kind==='error'?'alert':'status'} aria-busy={kind==='loading'}><h3>{title}</h3>{children}</div>;}
export function Skeleton(){return <div className="ui-skeleton" aria-label="Caricamento in corso" role="status"><span/><span/><span/></div>;}
export function EstimatePlaceholder(){return <section className="estimate-preview" aria-labelledby="estimate-heading"><div><Badge>Funzione in sviluppo</Badge><h2 id="estimate-heading">HouseID Estimate</h2><p>Il prezzo richiesto è un punto di partenza.<br/>La valutazione sarà un altro passo.</p><small>Il motore di stima non è ancora disponibile. Nessun valore è stato calcolato.</small></div><div className="estimate-placeholder"><ScanLine size={28}/><h3>Una stima, quando i dati lo permetteranno.</h3><dl>{[['Intervallo e valore centrale','Non disponibili'],['Prezzo stimato al m²','Non disponibile'],['Affidabilità della stima','Non valutata'],['Completezza dei dati','Non calcolata'],['Comparabili e classificazione','Non disponibili']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>La completezza descrive quanti dati possediamo. L’affidabilità descrive quanto è attendibile una stima: sono due misure diverse.</p></div></section>;}

export function IconButton({label,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){const id=useId();return <span className="ui-tooltip"><button type="button" aria-label={label} aria-describedby={id} {...props}>{children}</button><span id={id} role="tooltip">{label}</span></span>;}
