import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseFeature,parseCollection,deduplicate} from '../src/server/imports/bdtre-parser';
const feature={type:'Feature',properties:{uuid:'test-only-id',tp_str_nom:' VIA  ROMA ',civico_num:'0',civico_sub:'A',acc_pc_geo:'puntuale'},geometry:{type:'Point',coordinates:[400000,4970000]}};
test('conservative address normalization preserves zero, suffix and raw source',()=>{const r=parseFeature(feature,'acc_pc','fixture',0);assert.equal(r.street,'VIA ROMA');assert.equal(r.number,'0');assert.equal(r.suffix,'A');assert.equal(r.precision,'address');assert.deepEqual(r.raw,feature);});
test('missing fields remain null; approximate access not promoted',()=>{const r=parseFeature({...feature,properties:{uuid:'x',acc_pc_geo:'approssimato'}},'acc_pc','fixture',0);assert.equal(r.street,null);assert.equal(r.number,null);assert.equal(r.precision,'unknown');});
test('duplicates counted; conflicts quarantined',()=>{const a=parseFeature(feature,'acc_pc','f',0);assert.equal(deduplicate([a,{...a}]).duplicates,1);const b=parseFeature({...feature,properties:{...feature.properties,civico_num:'2'}},'acc_pc','f',1);assert.ok(deduplicate([a,b]).records[0].errors.includes('conflicting_duplicate'));});
test('malformed geometry, wrong type and missing identity rejected',()=>{assert.ok(parseFeature({...feature,geometry:{type:'Point',coordinates:[NaN,0]}},'acc_pc','f',0).errors.length);assert.ok(parseFeature(feature,'edifc','f',0).errors.length);assert.ok(parseFeature({...feature,properties:{}},'acc_pc','f',0).errors.includes('missing_uuid'));});
test('CRS must be declared and match original 32632',()=>{assert.throws(()=>parseCollection({type:'FeatureCollection',features:[feature]},'acc_pc','f'));const rows=parseCollection({type:'FeatureCollection',crs:{properties:{name:'urn:ogc:def:crs:EPSG::32632'}},features:[feature]},'acc_pc','raw-ref');assert.equal(rows[0].reference,'raw-ref');assert.equal(rows[0].hash.length,64);});
